#!/bin/sh
set -e

: "${CHECKOUT_URL:=https://pay.hotmart.com/H105816474H}"
: "${META_PIXEL_ID:=1480648363468725}"
: "${WHATSAPP_NUMBER:=5551993802574}"
: "${WHATSAPP_MESSAGE:=Olá, Tenho interesse na Lista de Fornecedores!}"
: "${PRICE_OLD:=R\$ 197,00}"
: "${PRICE_OLD_SHORT:=R\$197}"
: "${PRICE_OLD_ROUND:=R\$ 197}"
: "${PRICE_NEW_INT:=29}"
: "${PRICE_NEW_CENTS:=,90}"
: "${PRICE_INSTALLMENT:=4x de R\$ 8,14}"
: "${VALUE_STACK_TOTAL:=R\$ 341,00}"

export CHECKOUT_URL META_PIXEL_ID WHATSAPP_NUMBER WHATSAPP_MESSAGE PRICE_OLD PRICE_OLD_SHORT \
  PRICE_OLD_ROUND PRICE_NEW_INT PRICE_NEW_CENTS PRICE_INSTALLMENT VALUE_STACK_TOTAL

envsubst '${CHECKOUT_URL} ${META_PIXEL_ID} ${WHATSAPP_NUMBER} ${WHATSAPP_MESSAGE} ${PRICE_OLD} ${PRICE_OLD_SHORT} ${PRICE_OLD_ROUND} ${PRICE_NEW_INT} ${PRICE_NEW_CENTS} ${PRICE_INSTALLMENT} ${VALUE_STACK_TOTAL}' \
  < /usr/share/nginx/html/config.js.template \
  > /usr/share/nginx/html/config.js
