server {
    listen 80;
    root /usr/share/nginx/html;
    index Sale-Page-Customer-List-Premium.html;

    location / {
        try_files $uri $uri/ /Sale-Page-Customer-List-Premium.html;
    }

    gzip on;
    gzip_types text/css text/html application/javascript;
}
